### ISSUE TITLE
need help to use the correct syntax of wrapping running text

### ISSUE THREAD

**Issue by geohuz** [vijithassar/d3-textwrap#10]
I have the following text appending method:
```
      nodeEnter.append('text')
        .attr('x', '2')
        .attr('y', '1.2em')
        .text(function(d) {
          return d.name 
        })
```

I can't figure out how to use the textwrap function here.

**Comment by sarahlag** [comment]
If you still need help, here's how: (put right after your code)
```
d3.selectAll('text').each(function(d) {
     bounds = { /* define bounds */ };
     d3.select(this).textwrap(bounds); 
});

```

**Comment by vijithassar** [comment]
Thanks @sarahlag!

@geohuz, the syntax has changed for the current release of the plugin, which is meant for d3.js version 4, but this is the correct solution for the [older version](https://github.com/vijithassar/d3-textwrap/tree/e52a590e2d6d4db713b0353100c637723a5a6a95).
