### ISSUE TITLE
How to import or require after npm install?

### ISSUE THREAD

**Issue by stahlmanDesign** [vijithassar/d3-textwrap#14]
I've installed with NPM and I'd like to import or require in my ES6 file, but I'm not sure of the syntax.

I first include d3 v4 and confirm my chart works.
`import * as d3 from 'd3'`

But not sure how to import or require d3-textwrap. A few things that don't work:

`import textwrap from 'd3-textwrap'`
`import { textwrap } from 'd3-textwrap'`
`import { d3, textwrap } from 'd3-textwrap'`
`require("d3-textwrap")`
`var require("d3-textwrap")`
`var d3Textwrap = require("d3-textwrap")`

**Comment by protoEvangelion** [comment]
It would be great to document how to properly **import** this package using **es6 imports**.  Is it possible to do this with d3-textwrap?

**Comment by Quadrophone** [comment]
This worked for me:

```
import { textwrap } from 'd3-textwrap';
d3.textwrap = textwrap;
```

or:

```
const textwrap = require('d3-textwrap');
d3.textwrap = textwrap.textwrap;
```

**Comment by qbunt** [comment]
Just added your suggestion to a PR in the readme, worked well for me @Quadrophone, thanks!

**Comment by grajamanickam** [comment]
iam developing a custom visual and I want to use the d3-textwrap. the above code is not working for me.  Iam getting this error "cannot find name 'require'"

**Comment by erikstarck** [comment]
This works for me, building a Vue component and Mixin (Laravel) to build:
```
import * as d3Base  from 'd3';
import {textwrap} from 'd3-textwrap'

const d3 = Object.assign(d3Base, { textwrap })
```

**Comment by BhuvitaSisodiya** [comment]
Hi when i am using below command 
npm install @types/d3-textwrap
it says '@types/d3-textwrap@latest' is not in the npm registry.
I want to use wrap function in my typescript file.
Can you please help me with this.

**Comment by vijithassar** [comment]
I've [added this](https://github.com/vijithassar/d3-textwrap/commit/06b0c80b23b1d2f42186bc6086e1bb9a5679abe5) to the [documentation](https://github.com/vijithassar/d3-textwrap/blob/master/README.md#import).

**Comment by vijithassar** [comment]
To my knowledge there are no type definitions for this yet @BhuvitaSisodiya.
