### ISSUE TITLE
import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by carmenbranje** [vijithassar/d3-textwrap#15]
I included d3-textwrap.js in my index file but I get the following error:

line 1 - import declarations may only appear at top level of a module

**Comment by woodz-** [comment]
Might be helpful to document a bit deeper and separate user groups:

- npm users: do this
- browser users: do that

For me it's not clear on how to use it in browser. Which file to include in <script> tags? Will I need to browserify first? Then which file to start over? etc.

Had a couple of error prone tries with browserify: 
```
export {selection, select} from 'd3-selection';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by vijithassar** [comment]
I've [added this](https://github.com/vijithassar/d3-textwrap/commit/06b0c80b23b1d2f42186bc6086e1bb9a5679abe5) to the [documentation](https://github.com/vijithassar/d3-textwrap/blob/master/README.md#import).
