### ISSUE TITLE
d3 text-wrap plugin changes coordinates

### ISSUE THREAD

**Issue by Githamza** [vijithassar/d3-textwrap#19]
I would wrap dynamic text.
I tried to apply what mentioned in doc

let textWrap;
let d3Text1 = d3.selectAll(stations);
textWrap = d3wrap.textwrap().bounds({ height: 100, width: 100 });
d3Text1.call(textWrap); // commenting this will make initial position but no wrap

the plugin is working but the text is getting moved from it's initial position

![image](https://user-images.githubusercontent.com/11578288/61398381-2f304c80-a8cc-11e9-9f7c-564383ead009.png)

here a reproduction on [stackblitz](https://stackblitz.com/edit/angular-d3-textplugin?file=src/app/app.component.ts)

**Comment by sarahgp** [comment]
I also have this problem. It looks like when a `foreignObject` is created, it is given x and y values of 0.
