### ISSUE TITLE
Doesn't select right element when <text> element is not only one within parent

### ISSUE THREAD

**Issue by sypl** [vijithassar/d3-textwrap#4]
Given this,
```
<g>
  <g class="tick" transform="translate(123,0)" style="opacity: 1;">
    <line y2="-168" x2="0"></line>
    <text dy=".71em" y="7" x="0" style="text-anchor: middle;">2009</text>
  </g>
  <g class="tick" transform="translate(246,0)" style="opacity: 1;">
    <line y2="-168" x2="0"></line>
    <text dy=".71em" y="7" x="0" style="text-anchor: middle;">2010</text>
  </g>
  <text class="nv-axislabel" text-anchor="middle" y="36" x="307.5">Level 2</text>
</g>
```

if I try to do something like this: `d3.select('.nv-x .nv-axis .nv-axislabel').textwrap({x:0,y:0,width:200,height:200})`

then this code selects the wrong text node, because it looks for the first text node under the parent, which is not the one that's been wrapped.

```
var wrap_with_foreignobjects = function(item) {
                // establish variables to quickly reference target nodes later
                var parent = d3.select(item[0].parentNode);
                var text_node = parent.select('text');
```

**Comment by vijithassar** [comment]
Hmm, is there a reason why selecting the text nodes first with select() or selectAll() won't work for you in this scenario?

`d3.select('.nv-x .nv-axis .nv-axislabel').select('text').textwrap({x:0,y:0,width:200,height:200})`

It'd be nice for this plugin to search for the text nodes under any D3 selection, of course, just trying to understand the use case here. To be honest, part of me worries that there's some edge case I'm not quite thinking of at the moment, and wonders whether the better fix might be to fail outright and report an error with console.log() if you try to run the textwrap() method on a D3 selection that is something other than a text node, such as the <g> ticks in the example above.

**Comment by ronnievk** [comment]
I ran into the same issue. I changed the line (181) `var text_node = parent.select('text');` to `var text_node = d3.select(item[0]);`
