### ISSUE TITLE
textwrap doesn't work with d3.selectAll()

### ISSUE THREAD

**Issue by jfstephe** [vijithassar/d3-textwrap#9]
If you do:

`d3.selectAll('text').textwrap(bounds, padding);`

it only affects the first element that matches the selector.

Workaround:
`
d3.selectAll('text').each(function(d) {
                d3.select(this).textwrap(bounds, padding);
            });
`

**Comment by vijithassar** [comment]
Thanks for reporting this! Guess I'd screwed up on the earlier version of this plugin, but the current version for d3 version 4 does automatically iterate using .each() as you suggest.
